# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9aWYsHbwv2OYG-kJSTrDH5yW6dvnkrj
"""

import streamlit as st
import pickle
import re
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import os
import gdown

st.set_page_config(page_title="Comment Toxicity Detector", page_icon="🛡️", layout="wide")

MODEL_PATH = 'toxicity_model.h5'
MODEL_DRIVE_URL = 'https://drive.google.com/file/d/12aAMps4MvNvwln5yMl06DthLXFf1tJfn/view?usp=drive_link'

@st.cache_resource
def load_artifacts():
    if not os.path.exists(MODEL_PATH):
        gdown.download(url=MODEL_DRIVE_URL, output=MODEL_PATH, quiet=False, fuzzy=True)
    model = load_model(MODEL_PATH)
    with open('tokenizer.pkl', 'rb') as f:
        tokenizer = pickle.load(f)
    with open('config.pkl', 'rb') as f:
        config = pickle.load(f)
    return model, tokenizer, config

model, tokenizer, config = load_artifacts()
label_cols = config['label_cols']
max_len = config['max_len']

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def predict_toxicity(text):
    cleaned = clean_text(text)
    seq = tokenizer.texts_to_sequences([cleaned])
    padded = pad_sequences(seq, maxlen=max_len, padding='post', truncating='post')
    proba = model.predict(padded, verbose=0)[0]
    return dict(zip(label_cols, proba))

st.title("🛡️ Comment Toxicity Detector")
st.caption("Deep learning model (Bi-LSTM) for real-time toxic comment classification")

tab1, tab2, tab3 = st.tabs(["🔍 Single Comment", "📁 Bulk Upload (CSV)", "📊 Model Info"])

with tab1:
    st.subheader("Analyze a single comment")
    user_input = st.text_area("Enter a comment:", height=100, placeholder="Type or paste a comment here...")
    if st.button("Analyze", type="primary"):
        if user_input.strip():
            results = predict_toxicity(user_input)
            overall_toxic = any(v > 0.5 for v in results.values())
            if overall_toxic:
                st.error("⚠️ This comment was flagged as TOXIC")
            else:
                st.success("✅ This comment appears non-toxic")

            df_results = pd.DataFrame(results.items(), columns=['Category', 'Score'])
            df_results['Flagged'] = df_results['Score'] > 0.5
            st.bar_chart(df_results.set_index('Category')['Score'])
            st.dataframe(df_results, use_container_width=True)
        else:
            st.warning("Please enter a comment first.")

with tab2:
    st.subheader("Bulk prediction from CSV")
    uploaded_file = st.file_uploader("Upload a CSV with a text column", type=['csv'])
    if uploaded_file:
        bulk_df = pd.read_csv(uploaded_file)
        text_column = st.selectbox("Select the text column:", bulk_df.columns)
        if st.button("Run Bulk Prediction"):
            with st.spinner("Predicting..."):
                preds = bulk_df[text_column].astype(str).apply(predict_toxicity)
                preds_df = pd.DataFrame(preds.tolist())
                result_df = pd.concat([bulk_df, preds_df], axis=1)
            st.dataframe(result_df, use_container_width=True)
            csv = result_df.to_csv(index=False).encode('utf-8')
            st.download_button("Download Results CSV", csv, "toxicity_predictions.csv", "text/csv")

with tab3:
    st.subheader("Model Details")
    st.write(f"**Architecture:** Bidirectional LSTM")
    st.write(f"**Label categories:** {', '.join(label_cols)}")
    st.write(f"**Max sequence length:** {max_len} tokens")
    st.write("**Sample test cases:**")
    samples = [
        "You are amazing, thank you for sharing this!",
        "I disagree with your opinion but respect it.",
    ]
    for s in samples:
        res = predict_toxicity(s)
        st.write(f"- *\"{s}\"* → max score: {max(res.values()):.3f}")